version: '3.8'

services:
  postgres_user:
    image: 'postgres:13.8-alpine'
    container_name: userServiceApp
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword

    volumes:
      - postgres_user:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg-isready U postgres" ]
      start_period: 15s
      timeout: 3s
      interval: 10s
      retries: 12

volumes:
  postgres_user:
